package com.zhixing.staffid.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhixing.staffid.entity.Content;
import com.zhixing.staffid.entity.Note;

import com.zhixing.staffid.dao.ContentDao;
import com.zhixing.staffid.dao.NoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contentDaoConfig;
    private final DaoConfig noteDaoConfig;

    private final ContentDao contentDao;
    private final NoteDao noteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contentDaoConfig = daoConfigMap.get(ContentDao.class).clone();
        contentDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        contentDao = new ContentDao(contentDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);

        registerDao(Content.class, contentDao);
        registerDao(Note.class, noteDao);
    }
    
    public void clear() {
        contentDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
    }

    public ContentDao getContentDao() {
        return contentDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

}
