package com.zhixing.staffid.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CONTENT".
 */
@Entity
public class Content {

    @Id
    private Long id;

    @NotNull
    private String item_id;
    private Integer category;
    private String title;
    private String img_url;
    private String pic_info;
    private String words_info;
    private String subtitle;
    private java.util.Date post_date;

    @Generated
    public Content() {
    }

    public Content(Long id) {
        this.id = id;
    }

    @Generated
    public Content(Long id, String item_id, Integer category, String title, String img_url, String pic_info, String words_info, String subtitle, java.util.Date post_date) {
        this.id = id;
        this.item_id = item_id;
        this.category = category;
        this.title = title;
        this.img_url = img_url;
        this.pic_info = pic_info;
        this.words_info = words_info;
        this.subtitle = subtitle;
        this.post_date = post_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getItem_id() {
        return item_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setItem_id(@NotNull String item_id) {
        this.item_id = item_id;
    }

    public Integer getCategory() {
        return category;
    }

    public void setCategory(Integer category) {
        this.category = category;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImg_url() {
        return img_url;
    }

    public void setImg_url(String img_url) {
        this.img_url = img_url;
    }

    public String getPic_info() {
        return pic_info;
    }

    public void setPic_info(String pic_info) {
        this.pic_info = pic_info;
    }

    public String getWords_info() {
        return words_info;
    }

    public void setWords_info(String words_info) {
        this.words_info = words_info;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public java.util.Date getPost_date() {
        return post_date;
    }

    public void setPost_date(java.util.Date post_date) {
        this.post_date = post_date;
    }

}
